package com.example.cs175proj;

import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.navigation.NavController;
import androidx.navigation.fragment.NavHostFragment;

import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;

import java.util.ArrayList;

/**
 * Fragment for creating posts
 */
public class CreatePostFragment extends Fragment {

    /**
     * Empty constructor
     */
    public CreatePostFragment() {
    }

    /**
     * Autogenerated onCreate method
     * @param savedInstanceState
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    /**
     * onCreateView, inflates the view and returns it, sets up the EditTexts and the submit button for the fragment
     * @param inflater
     * @param container
     * @param savedInstanceState
     * @return the inflated view
     */
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_create_post, container, false);
        EditText title = view.findViewById(R.id.create_title);
        EditText content = view.findViewById(R.id.create_content);
        Button submit = view.findViewById(R.id.submit_button);

        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(!checkLength(title.getText().toString()) || !checkLength(content.getText().toString())){
                    warnLength();
                }else if(!checkTitleLength(title.getText().toString())){
                    warnTitleLength();
                }else if(!checkContentLength(content.getText().toString())){
                    warnContentLength();
                } else {
                    LogActivity la = (LogActivity) getActivity();
                    int uID = la.session.getSession();
                    User u = new User("null", "null", "null");
                    User temp = la.getUser(uID);
                    if (temp != null) {
                        u = temp;
                    }
                    Post p = new Post(u, content.getText().toString(), title.getText().toString());
                    la.insertPost(p);
                    goBackToList();
                }
            }
        });

        return view;
    }

    /**
     * Uses nav to go back to the list of posts
     */
    public void goBackToList() {
        NavController nav = NavHostFragment.findNavController(this);
        nav.navigate(R.id.action_createPostFragment_to_itemFragment);
    }

    /**
     * Checks the length of a string to see if it is an empty string
     * @param s the string to be checked
     * @return true of the string is empty, false otherwise
     */
    public boolean checkLength(String s){
        if(s.length() < 1){
            return false;
        }
        return true;
    }

    /**
     * Checks if a String is over 60 characters
     * @param s the String th be checked
     * @return true if the String is 60 characters or less, false otherwise
     */
    public boolean checkTitleLength(String s){
        if(s.length() <= 60){
            return true;
        }
        return false;
    }

    /**
     * Checks if a String is over 300 characters
     * @param s the String to be checked
     * @return true if the String is 300 characters or less, false otherwise
     */
    public boolean checkContentLength(String s){
        if(s.length() <= 300){
            return true;
        }
        return false;
    }

    /**
     * Displays a warning if a user tries to create a post with a empty title or content
     */
    private void warnLength() {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setTitle("Field Length");
        builder.setMessage("Fields must be at least 1 character");
        builder.create().show();
    }

    /**
     * Displays a warning if a user tries to create a post with a title over 60 characters
     */
    private void warnTitleLength() {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setTitle("Title Field Length");
        builder.setMessage("Title cannot exceed 60 characters");
        builder.create().show();
    }

    /**
     * Displays a warning if a user tries to create a post with it's content being over 300 characters
     */
    private void warnContentLength(){
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setTitle("Content Field Length");
        builder.setMessage("Content cannot exceed 300 characters");
        builder.create().show();
    }

}